var groupes_locaux = [
    { "name": "Groupe Local Alsace", "type": "Groupe Local", "lat": 48.57336129083668, "lng": 7.752806568453742, "address": "Alsace", "postcode": "", "city": "Strasbourg", "website": "", "phone": "", "email": "contact-alsace@reseau-salariat.info", "summary": "Groupe local pour l'Alsace." },
    { "name": "Groupe Local Aquitaine", "type": "Groupe Local", "lat": 44.8420266029774, "lng": -0.5815520693298535, "address": "Aquitaine", "postcode": "", "city": "Bordeaux", "website": "", "phone": "", "email": "contact-aquitaine@reseau-salariat.info", "summary": "Groupe local pour l'Aquitaine." },
    { "name": "Groupe Local Avignon-Orange-Carpentras (AOC)", "type": "Groupe Local", "lat": 43.94894220546615, "lng": 4.808878174142274, "address": "Avignon-Orange-Carpentras", "postcode": "", "city": "Avignon", "website": "", "phone": "", "email": "contact-aoc@reseau-salariat.info", "summary": "Groupe local pour Avignon, Orange et Carpentras." },
    /*{ "name": "Groupe Local Auvergne", "type": "Groupe Local", "lat": 45.7772, "lng": 3.0870, "address": "Auvergne", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-auvergne@reseau-salariat.info", "summary": "Groupe local pour l'Auvergne." },*/
    { "name": "Groupe Local Belgique", "type": "Groupe Local", "lat": 50.847507383521595, "lng": 4.356874232605811, "address": "", "postcode": "", "city": "Bruxelles", "website": "", "phone": "", "email": "contact-belgique@reseau-salariat.info", "summary": "Groupe local pour la Belgique." },

    /*{ "name": "Groupe Local Bretagne", "type": "Groupe Local", "lat": 48.1173, "lng": -1.6778, "address": "Bretagne", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-bretagne@reseau-salariat.info", "summary": "Groupe local pour la Bretagne." },*/
    { "name": "Groupe Local Finistère", "type": "Groupe Local", "lat": 48.39040524157299, "lng": -4.486541962738135, "address": "", "postcode": "29000", "city": "Brest", "website": "", "phone": "", "email": "contact-29@reseau-salariat.info", "summary": "Groupe local du Finistère." },
    { "name": "Groupe Local Ille-et-Vilaine", "type": "Groupe Local", "lat": 48.117416838818045, "lng": -1.6803761300285887, "address": "", "postcode": "35000", "city": "Rennes", "website": "", "phone": "", "email": "contact-35@reseau-salariat.info", "summary": "Groupe local d'Ille-et-Vilaine'." },
    { "name": "Groupe Local Morbihan", "type": "Groupe Local", "lat": 47.6584949382466, "lng": -2.7597815705565716, "address": "", "postcode": "56000", "city": "Vannes", "website": "", "phone": "", "email": "contact-56@reseau-salariat.info", "summary": "Groupe local du Morbihan." },
    /*{ "name": "Groupe Local Bourgogne", "type": "Groupe Local", "lat": 47.3220, "lng": 5.0415, "address": "Bourgogne", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-bourgogne@reseau-salariat.info", "summary": "Groupe local pour la Bourgogne." },*/
    
    { "name": "Groupe Local Bressuire-Cholet (Cholet)", "type": "Groupe Local", "lat": 47.058730613871134, "lng": -0.792885699236633, "address": "", "postcode": "", "city": "Cholet/Bressuire", "website": "", "phone": "", "email": "contact-bressuire-cholet@reseau-salariat.info", "summary": "Groupe local pour Bressuire, Cholet, Angers et Nantes." },
    { "name": "Groupe Local Pays-de-la-Loire", "type": "Groupe Local", "lat": 47.41719757258201, "lng": -0.9816069765565267, "address": "Pays-de-la-Loire", "postcode": "", "city": "Nantes/Angers", "website": "", "phone": "", "email": "contact-pays-de-la-loire@reseau-salariat.info", "summary": "Groupe local pour les Pays-de-la-Loire." },

    { "name": "Groupe Local Cantal", "type": "Groupe Local", "lat": 45.11850558006214, "lng": 2.6483008436716755, "address": "Cantal", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-cantal@reseau-salariat.info", "summary": "Groupe local pour le Cantal." },
    { "name": "Groupe Local Centre", "type": "Groupe Local", "lat": 47.57344520717716, "lng": 1.606472309715626, "address": "Centre", "postcode": "", "city": "Orléans, Tours, Bourges", "website": "", "phone": "", "email": "contact-centre@reseau-salariat.info", "summary": "Groupe local pour le Centre." },
    /*{ "name": "Groupe Local Champagne-Ardennes", "type": "Groupe Local", "lat": 49.2743, "lng": 4.2517, "address": "Champagne-Ardennes", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-champagne-ardennes@reseau-salariat.info", "summary": "Groupe local pour la Champagne-Ardennes." },*/
    { "name": "Groupe Local Corrèze", "type": "Groupe Local", "lat": 45.37202863567862, "lng": 1.8747573441894392, "address": "Corrèze", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-correze@reseau-salariat.info", "summary": "Groupe local pour la Corrèze." },
    { "name": "Groupe Local Corse", "type": "Groupe Local", "lat": 42.17828133613821, "lng": 9.116787909000637, "address": "Corse", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-corse@reseau-salariat.info", "summary": "Groupe local pour la Corse." },
    { "name": "Groupe Local Drôme-Ardèche", "type": "Groupe Local", "lat": 44.55515162832607, "lng": 4.755003533217421, "address": "Drôme-Ardèche", "postcode": "26200", "city": "Montélimar", "website": "", "phone": "", "email": "contact-drome-ardeche@reseau-salariat.info", "summary": "Groupe local pour la Drôme et l'Ardèche." },
    /*{ "name": "Groupe Local Essonne", "type": "Groupe Local", "lat": 48.632, "lng": 2.446, "address": "Essonne", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-essonne@reseau-salariat.info", "summary": "Groupe local pour l'Essonne." },*/
    { "name": "Groupe Local Franche-Comté", "type": "Groupe Local", "lat": 47.23865801745064, "lng": 6.021166287775814, "address": "", "postcode": "", "city": "Besançon", "website": "", "phone": "", "email": "contact-franche-comte@reseau-salariat.info", "summary": "Groupe local pour la Franche-Comté." },
    { "name": "Groupe Local Grand Paris", "type": "Groupe Local", "lat": 48.85811925318083, "lng": 2.3470076729537515, "address": "Grand Paris", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-grand-paris@reseau-salariat.info", "summary": "Groupe local pour le Grand Paris." },
    /*{ "name": "Groupe Local Île-de-France", "type": "Groupe Local", "lat": 48.8566, "lng": 2.3522, "address": "Île-de-France", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-ile‐de‐france@reseau-salariat.info", "summary": "Groupe local pour l'Île-de-France." },*/
    { "name": "Groupe Local Grand Rhône", "type": "Groupe Local", "lat": 45.763593229645274, "lng": 4.833736244895295, "address": "Grand Rhône", "postcode": "", "city": "Lyon", "website": "", "phone": "", "email": "contact-grand-rhone@reseau-salariat.info", "summary": "Groupe local pour le Grand Rhône." },
    { "name": "Groupe Local Grenoble (Rhône-Alpes)", "type": "Groupe Local", "lat": 45.188339474567165, "lng": 5.722577313379496, "address": "", "postcode": "", "city": "Grenoble", "website": "", "phone": "", "email": "contact-rhone-alpes-grenoble@reseau-salariat.info", "summary": "Groupe local pour Grenoble." },
    { "name": "Groupe Local Rhône-Alpes", "type": "Groupe Local", "lat": 45.188339474567165, "lng": 5.722577313379496, "address": "Rhône-Alpes", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-rhone-alpes@reseau-salariat.info", "summary": "Groupe local pour Rhône-Alpes." },

    { "name": "Groupe Local Guadeloupe", "type": "Groupe Local", "lat": 16.237003532384858, "lng": -61.53677093448313, "address": "", "postcode": "", "city": "Pointe-à-Pitre", "website": "", "phone": "", "email": "contact-pyrenees-atlantiques@reseau-salariat.info", "summary": "Groupe local pour les Pyrénées-Atlantiques." },

    { "name": "Groupe Local Languedoc-Roussillon", "type": "Groupe Local", "lat": 43.610407471048205, "lng": 3.878267881360415, "address": "", "postcode": "", "city": "Montpellier", "website": "", "phone": "", "email": "contact-languedoc-roussillon@reseau-salariat.info", "summary": "Groupe local pour le Languedoc-Roussillon." },
    { "name": "Groupe Local Les-Deux-Savoie", "type": "Groupe Local", "lat": 45.56490476035864, "lng": 5.92111014078068, "address": "", "postcode": "", "city": "Chambéry", "website": "", "phone": "", "email": "contact-les-deux-savoie@reseau-salariat.info", "summary": "Groupe local pour Les-Deux-Savoie." },
    /*{ "name": "Groupe Local Limousin", "type": "Groupe Local", "lat": 45.83385925953506, "lng": 1.2607224463116207, "address": "", "postcode": "", "city": "Limoges", "website": "", "phone": "", "email": "contact-limousin@reseau-salariat.info", "summary": "Groupe local pour le Limousin." },*/
    { "name": "Groupe Local Lorraine", "type": "Groupe Local", "lat": 49.01271005759512, "lng": 6.477631294132395, "address": "Lorraine", "postcode": "", "city": "Nancy/Metz", "website": "", "phone": "", "email": "contact-lorraine@reseau-salariat.info", "summary": "Groupe local pour la Lorraine." },
    { "name": "Groupe Local Lubéron", "type": "Groupe Local", "lat": 43.838539016254664, "lng": 5.0363623980113, "address": "", "postcode": "", "city": "Cavaillon", "website": "", "phone": "", "email": "contact-lorraine@reseau-salariat.info", "summary": "Groupe local pour la Lorraine." },
    { "name": "Groupe Local Midi-Pyrénées", "type": "Groupe Local", "lat": 43.605645896016235, "lng": 1.4373023665277198, "address": "", "postcode": "", "city": "Toulouse", "website": "", "phone": "", "email": "contact-midi-pyrenees@reseau-salariat.info", "summary": "Groupe local pour Midi-Pyrénées." },
    { "name": "Groupe Local Nord-Pas-de-Calais (NPDC)", "type": "Groupe Local", "lat": 50.62410406835024, "lng": 3.066466466045813, "address": "", "postcode": "", "city": "Lille", "website": "", "phone": "", "email": "contact-npdc@reseau-salariat.info", "summary": "Groupe local pour le Nord-Pas-de-Calais." },
    { "name": "Groupe Local Normandie", "type": "Groupe Local", "lat": 49.1818285959385, "lng": -0.37018351335176103, "address": "", "postcode": "", "city": "Caen", "website": "", "phone": "", "email": "contact-normandie@reseau-salariat.info", "summary": "Groupe local pour la Normandie." },
    /*{ "name": "Groupe Local Oise", "type": "Groupe Local", "lat": 49.3988, "lng": 2.8235, "address": "Oise", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-oise@reseau-salariat.info", "summary": "Groupe local pour l'Oise." },*/
    
    { "name": "Groupe Local Alpes-Maritimes (PACA-06)", "type": "Groupe Local", "lat": 43.710362967490575, "lng": 7.260705098999696, "address": "Alpes-Maritimes", "postcode": "", "city": "Nice", "website": "", "phone": "", "email": "contact-paca-06@reseau-salariat.info", "summary": "Groupe local pour les Alpes-Maritimes." },
    { "name": "Groupe Local Bouches-du-Rhône (PACA-13)", "type": "Groupe Local", "lat": 43.29841487355402, "lng": 5.373009728878471, "address": "Bouches-du-Rhône", "postcode": "", "city": "Marseille", "website": "", "phone": "", "email": "contact-paca-13@reseau-salariat.info", "summary": "Groupe local pour les Bouches-du-Rhône." },
    /*{ "name": "Groupe Local Provence-Alpes-Côte d’Azur", "type": "Groupe Local", "lat": 43.9352, "lng": 6.0679, "address": "Provence-Alpes-Côte d’Azur", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-paca@reseau-salariat.info", "summary": "Groupe local pour la Provence-Alpes-Côte d’Azur." },*/
    { "name": "Groupe Local Pays Basque Sud Landes", "type": "Groupe Local", "lat": 43.49356590924906, "lng": -1.4719088243720524, "address": "", "postcode": "", "city": "Bayonne", "website": "", "phone": "", "email": "contact-pays-basque-sud-landes@reseau-salariat.info", "summary": "Groupe local pour le Pays Basque Sud Landes." },
    { "name": "Groupe Local Picardie", "type": "Groupe Local", "lat": 49.89418275056398, "lng": 2.292215365037253, "address": "", "postcode": "", "city": "Amiens", "website": "", "phone": "", "email": "contact-picardie@reseau-salariat.info", "summary": "Groupe local pour la Picardie." },
    { "name": "Groupe Local Poitou-Charentes", "type": "Groupe Local", "lat": 46.57954968497033, "lng": 0.340900592242836, "address": "Poitou-Charentes", "postcode": "", "city": "Poitiers", "website": "", "phone": "", "email": "contact-poitou-charentes@reseau-salariat.info", "summary": "Groupe local pour le Poitou-Charentes." },
    { "name": "Groupe Local Vienne (Poitou-Charentes)", "type": "Groupe Local", "lat": 45.52555702238737, "lng": 4.874152492493333, "address": "Vienne", "postcode": "", "city": "", "website": "", "phone": "", "email": "contact-vienne@reseau-salariat.info", "summary": "Groupe local pour la Vienne." },
    { "name": "Groupe Local Puy-de-Dôme", "type": "Groupe Local", "lat": 45.793167349971625, "lng": 3.0804146596914896, "address": "Puy-de-Dôme", "postcode": "", "city": "Clermont-Ferrand", "website": "", "phone": "", "email": "contact-puy-de-dome@reseau-salariat.info", "summary": "Groupe local pour le Puy-de-Dôme." },
    { "name": "Groupe Local Pyrénées-Atlantiques", "type": "Groupe Local", "lat": 43.295645940254744, "lng": -0.3731595423160559, "address": "Pyrénées-Atlantiques", "postcode": "", "city": "Pau", "website": "", "phone": "", "email": "contact-pyrenees-atlantiques@reseau-salariat.info", "summary": "Groupe local pour les Pyrénées-Atlantiques." },
    { "name": "Groupe Local Suisse (Genève/Lausanne)", "type": "Groupe Local", "lat": 46.48153661227457, "lng": 6.318108353591471, "address": "", "postcode": "", "city": "Genève & Lausanne", "website": "", "phone": "", "email": "contact-pyrenees-atlantiques@reseau-salariat.info", "summary": "Groupe local pour les Pyrénées-Atlantiques." }
];
