// https://securite-sociale-alimentation.org/les-dynamiques-locales/carte-des-initiatives-locales-de-la-ssa/
var initiatives_ssa = [
    {
        "name": "Soli’Doume",
        "type": "initiative SSA",
        "Structures porteuses": ["ADML63", "le CRESNA", "VRAC Clermont-Ferrand", "Les Petits Débrouillards Auvergne"],
        "Territoire d’expérimentation": "Clermont-Ferrand",
        "Partenaires": ["CRESNA (coopérative)", "CISCA (recherche)"],
        "lat": 45.7741254,
        "lng": 3.0842469,
        "address": "Rue Meissonnier, 63000 Clermont-Ferrand, France Auvergne-Rhône-Alpes",
        "postcode": "63000",
        "city": "Clermont-Ferrand",
        "website": "https://securite-sociale-alimentation.org/initiative/la-doume/",
        "phone": "",
        "email": "",
        "summary": "L’équipe de l’Association pour le Développement des Monnaies Locales dans le Puy-de-Dôme a mis en place un travail de réflexion auprès de ses membres pour permettre l’accès de tous à une alimentation de qualité. (Monnaie Locale, coopérative)",
        "URLs": [
            "www.cresna-intermediation.com",
            "www.doume.org"
        ]
    },
    {
        "name": "La cagette verte",
        "type": "initiative SSA",
        "Structures porteuses": ["ICARE - Association ICARE"],
        "Territoire d’expérimentation": "Saint-Quentin-en-Yvelines",
        "Partenaires": ["La faculté de Saint-Quentin-en-Yvelines"],
        "lat": 48.77888699840781,
        "lng": 2.045719679701665,
        "address": "Maison de l'étudiant 1 Allée de l'Astronomie, 78280 Guyancourt, France Île-de-France",
        "postcode": "78280",
        "city": "Guyancourt",
        "website": "https://securite-sociale-alimentation.org/initiative/la-cagette-verte/",
        "phone": "",
        "email": "",
        "summary": "La Cagette verte c’est un système d’AMAP à prix différencié organisé par et pour des étudiants!",
        "URLs": ["https://www.facebook.com/AssociationIcare"]
    },
    {
        "name": "Groupe local SSA Sud Ouest IDF",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": [],
        "Territoire d’expérimentation": "Versailles, Saint-Quentin-en-Yvelines, Saclay",
        "Partenaires": [],
        "lat": 48.788247377211704,
        "lng": 2.0473564968914766,
        "address": "1 Av. des Prés, 78180 Montigny-le-Bretonneux, France",
        "postcode": "78180",
        "city": "Montigny-le-Bretonneux",
        "website": "https://securite-sociale-alimentation.org/initiative/groupe-local-vsqy-saclay/",
        "phone": "",
        "email": "",
        "summary": "Déterminé à porter la proposition de Sécurité sociale de l’alimentation un groupe de militants et militantes s’organisent pour diffuser l’idée de Sécurité Sociale de l’Alimentation sur le territoire du sud Ouest de l’île de France. Plusieurs actions ont été mises en place : porteurs de paroles, ateliers de discussions, arpentages de livres, journées d’autoformation sur la sécurité sociale de l’alimentation etc … ",
        "URLs": []
    },
    {
        "name": "Manger Demain",
        "type": "initiative SSA",
        "Structures porteuses": ["Association - initiative locale vers une SSA"],
        "Territoire d’expérimentation": "Métropole Rouen Normandie / Région Normandie",
        "Partenaires": ["Le Producteur Local", "la Dantine", "Triticum", "Le Champ des Possibles", "Alternoo", "Groupe Nutriset", "Action Contre la Faim", "Chaire Unesco Alimentation du Monde"],
        "lat": 49.4432,
        "lng": 1.0993,
        "address": "Rouen",
        "postcode": "76000",
        "city": "Rouen",
        "website": "https://securite-sociale-alimentation.org/initiative/manger-demain/",
        "phone": "",
        "email": "",
        "summary": "Manger Demain, est un projet dédié à la sécurité alimentaire durable sur le territoire. L'objet du projet est de fédérer les acteurs locaux des systèmes alimentaires durables dans une approche systémique, pour accélérer l'évolution des modes de consommation alimentaires dans un enjeu de santé publique, et concevoir et expérimenter des systèmes d'accès pour tous à une alimentation durable dans un enjeu de droit à l'alimentation.",
        "URLs": []
    },
    {
        "name": "La Collab Solidaire",
        "type": "initiative SSA",
        "Structures porteuses": ["Association - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Hauts-de-France",
        "Partenaires": ["CSC Etouvie", "CS Elbeuf", "Relai social", "communes Helemmes", "Lille", "Flixecourt", "L’Etoile"],
        "lat": 50.6292,
        "lng": 3.0573,
        "address": "Lille",
        "postcode": "59000",
        "city": "Lille",
        "website": "https://securite-sociale-alimentation.org/initiative/collab-solidaire/",
        "phone": "",
        "email": "",
        "summary": "Mise en relation de producteurs locaux et d’associations pour proposer des produits de qualité à des prix accessibles ou gratuitement et sans condition selon les partenariats.",
        "URLs": []
    },
    {
        "name": "SSEA Trièves",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["CERES - groupe local et initiative de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Isère (38)",
        "Partenaires": [],
        "lat": 44.80092651475182,
        "lng": 5.647876014197057,
        "address": "Le Percy, 38930 Le Percy, Auvergne-Rhône-Alpes",
        "postcode": "38930",
        "city": "Le Percy",
        "website": "https://securite-sociale-alimentation.org/initiative/ssea-38/",
        "phone": "",
        "email": "associationceres@riseup.net",
        "summary": "Un collectif informel, porté par le CERES, qui regroupe de nombreuses structures et acteur.ices dans le Trièves. Nous nous réunissons pour travailler au maillage de notre territoire en lien avec la SSA et sur la faisabilité de construire une expérimentation.",
        "URLs": []
    },
    {
        "name": "La MEUP",
        "type": "initiative SSA",
        "Structures porteuses": ["Structure de l'ESS - initiative locale vers une SSA"],
        "Territoire d’expérimentation": "Secteur Paray-Vieille-Poste (91) et secteur de Rungis (94)",
        "Partenaires": ["PTCE Coop Communs", "PTCE Pôle Noé Coopérative", "Coop Communs Coopérative", "Nature Nourricière", "Coopérative ESSCOOP", "Ville de Paray-Vieille-Poste", "Etablissement Territorial Grand-Orly-Seine-Bièvre", "Club Francilien de l'EFC", "Association Le Théâtre du Fil"],
        "lat": 48.71259543816393,
        "lng": 2.3616348553956517,
        "address": "Paray-Vieille-Poste",
        "postcode": "91550",
        "city": "Paray-Vieille-Poste",
        "website": "https://securite-sociale-alimentation.org/initiative/la-meup-pour-lacceleration-de-la-transition-alimentaire-ecologique-et-sociale/",
        "phone": "",
        "email": "",
        "summary": "",
        "URLs": [
            "https://www.facebook.com/profile.php?id=100076181847462"
        ]
    },
    {
        "name": "Expérimentation d’une SSA pour les étudiant·es des campus bordelais",
        "type": "initiative SSA",
        "Structures porteuses": ["Multiples - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Bordeaux Métropole",
        "Partenaires": ["La GEMME", "Le CREPAQ", "VRAC Université", "La cuvée des écolos", "Bordeaux Métropole", "CCAS de Bordeaux", "Université Bordeaux Montaigne", "Université de Bordeaux", "Ville de Pessac", "SICA Maraichère Bordelaise", "RESES", "La Fédération ATENA", "Ingénieurs Sans Frontières", "Bordeaux Sciences Agro", "une 20aine d’étudiant·es"],
        "lat": 44.83064510417015, 
        "lng": -0.5656059499354108,
        "address": "6 rue des Douves 33800 Bordeaux",
        "postcode": "33800",
        "city": "Bordeaux",
        "website": "https://securite-sociale-alimentation.org/initiative/projet-dexperimentation-dune-securite-sociale-de-lalimentation-pour-les-etudiant%c2%b7es-des-campus-bordelais/",
        "phone": "05 35 54 26 97",
        "email": "contact@crepaq.ong",
        "summary": "",
        "URLs": [
            "https://www.crepaq.ong/ssa%C3%A9tudiante",
        ]
    },
    {
        "name": "Collectif SSA 35",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["Collectif informel - groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Ille-et-Vilaine (35)",
        "Partenaires": [],
        "lat": 48.10387821015734,
        "lng": -1.67052829575318,
        "address": "Place de la Gare, 35000 Rennes, France",
        "postcode": "35000",
        "city": "Rennes",
        "website": "https://securite-sociale-alimentation.org/initiative/collectif-ssa-35/",
        "phone": "",
        "email": "collectif-ssa35@protonmail.com",
        "summary": "Le Collectif SSA 35 mène différentes actions pour faire connaître la proposition politique au grand public et mobiliser pour la création de la SSA.",
        "URLs": []
    },
    {
        "name": "Conserverie solidaire",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["Association - groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Saint-Denis, Stains",
        "Partenaires": [],
        "lat": 48.94598112524915,
        "lng": 2.3733663109107876,
        "address": "Saint-Denis/Stains, France",
        "postcode": "93240",
        "city": "Stains",
        "website": "https://securite-sociale-alimentation.org/initiative/conserverie-solidaire/",
        "phone": "",
        "email": "",
        "summary": "L’association collecte des fruits et légumes abîmés, les transforme en confitures et les re-distribue sur evènements ciblés ou auprès de population plus fragile telles que les étudiants de paris 8 ou les mineurs migrants.",
        "URLs": []
    },
    {
        "name": "Caisse de l’alimentation – Territoires à VivreS Grand Lyon",
        "type": "initiative SSA",
        "Structures porteuses": ["Association - initiative locale vers une SSA"],
        "Territoire d’expérimentation": "L'aire urbaine de Lyon, et en particulier l'arrondissement de Lyon 8",
        "Partenaires": ["VRAC Lyon Métropole", "le Groupement des Epiceries Sociales et Solidaires Rhône Alpes", "Habitat et Humanisme Rhône", "le Secours Catholique du Rhône", "le Groupement Régional Alimentaire de Proximité (GRAP)", "Récup & Gamelles", "Agribio", "l'UGESS", "la Fédération des Centres Sociaux du Rhône", "Bellebouffe", "Epi c'est bon", "l'ADDEAR", "le Réseau AMAP Aura", "Epicentre", "l'ISARA", "Bio à pro", "l'Espace Créateur de Solidarité de Saint-Fons", "la Maison Engagée et Solidaire de l'Alimentation", "les Jardins de Lucie", "la Métropole de Lyon"],
        "lat": 45.70769409083929,
        "lng": 4.869807983240429,
        "address": "41 avenue de la république, 69200 Vénissieux",
        "postcode": "69200",
        "city": "Lyon",
        "website": "https://securite-sociale-alimentation.org/initiative/caisse-de-lalimentation-territoires-a-vivres-grand-lyon/",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation dans la région lyonnaise.",
        "URLs": [
            "https://tav-lyon.xyz/?PagePrincipale",
            "https://www.linkedin.com/company/territoires-%C3%A0-vivres-grand-lyon/"
        ]
    },
    {
        "name": "SoliCagnole ",
        "type": "initiative SSA",
        "Structures porteuses": ["Association dédiée SoliCagnole - initiative locale vers une SSA"],
        "Territoire d’expérimentation": "Yonne et alentours",
        "Partenaires": ["Monnaie locale de l’Yonne La Cagnole", "Terre de Liens Bourgogne Franche-Comté", "Groupement des AgroBiologistes de l’Yonne"],
        "lat": 47.8588857621887,
        "lng": 3.4465699790519695,
        "address": "1 chemin de Charbuy 89113 Fleury-la-Vallée",
        "postcode": "89113",
        "city": "Fleury-la-Vallée",
        "website": "https://securite-sociale-alimentation.org/initiative/solicagnole/",
        "phone": "",
        "email": "secretariat@solicagnole.fr",
        "summary": "L’association Courts Circuits La Cagnole veut mettre en place une Sécurité Sociale de l’Alimentation, faisant de l’accessibilité à une alimentation soutenable et saine, un droit pour tous. Concrètement, chacun cotise chaque mois, selon ses moyens, de 10 à 100 Euros (ou plus) et tout le monde reçoit la même somme (la moyenne des cotisations) en monnaie locale, somme qui ne peut être dépensée qu’auprès de nos partenaires (producteurs et magasins bio, épiceries sociales et solidaires, épiceries indépendantes). Nous comptons co-créer une association dédiée à cette caisse, transparente et démocratique.",
        "URLs": [
            "https://solicagnole.fr/"
        ]
    },
    {
        "name": "Couserans (CAC09) – Ariège",
        "type": "initiative SSA",
        "Structures porteuses": ["Multiples - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Saint-Girons - Couserans en Ariège",
        "Partenaires": ["Croix Rouge", "Biocoop", "Secours Catholiques", "des élus à la mairie de St Girons", "une élue régionale sur la précarité alimentaire", "PNR des Pyrénées Ariégeoises et des bénévoles… + d’autres à solliciter! CAF", "projet de recherche participative HmmLab: INRAE (UMR Agir)", "ISTHIA", "PNR des Pyrénées Ariégeoises", "les Biches Volantes"],
        "lat": 42.982897312581485,
        "lng": 1.146062941970322,
        "address": "Saint-Girons",
        "postcode": "09200",
        "city": "Saint-Girons",
        "website": "https://securite-sociale-alimentation.org/initiative/citoyennete-et-alimentation-en-couserans-cac09-ariege/",
        "phone": "",
        "email": "",
        "summary": "Pour une alimentation digne et durable en Haute-Garonne.",
        "URLs": [
            "https://www.bio-ariege-garonne.fr/article/accessibilite-alimentaire"
        ]
    },
    {
        "name": "Groupe local SSA 38",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["Collectif informel - groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Isère (38)",
        "Partenaires": [],
        "lat": 45.187855539457395,
        "lng": 5.723092297478416,
        "address": "",
        "postcode": "",
        "city": "",
        "website": "https://securite-sociale-alimentation.org/initiative/groupe-local-ssa-38/",
        "phone": "",
        "email": "gl-ssa38@gresille.org",
        "summary": "",
        "URLs": []
    },
    {
        "name": "Caisse sociale de l’alimentation",
        "type": "initiative SSA",
        "Structures porteuses": ["Structure de l'ESS - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Saint-Etienne et alentours",
        "Partenaires": ["Terrain d’entente", "les Brigades de solidarité", "la Fourmilière", "la Cantine de quartier du Crêt-de-Roch", "les AMAPs de la Loire", "l’AMAP de Beaubrun", "De la Ferme au Quartier", "VRAC Saint Etienne", "la Biocoop des arcades", "Oasis", "Au terroir", "Danae care", "Coop’Sol42 et la Fabrique de la transition"],
        "lat": 45.4392528202996,
        "lng": 4.383286778007318,
        "address": "Saint-Étienne",
        "postcode": "42000",
        "city": "Saint-Étienne",
        "website": "https://securite-sociale-alimentation.org/initiative/collectif-solidarite-alimentaire-ssa42/",
        "phone": "",
        "email": "",
        "summary": "Initiative pour une sécurité sociale de l’alimentation à Saint-Étienne.",
        "URLs": []
    },
    {
        "name": "La Marmite Rouge",
        "type": "initiative SSA",
        "Structures porteuses": ["Association - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "12ème arrondissement et Est Parisien",
        "Partenaires": [],
        "lat": 45.4392528202996,
        "lng": 4.383286778007318,
        "address": "181 Avenue Daumesnil, 75012 Paris, France Île-de-France",
        "postcode": "75012",
        "city": "Paris",
        "website": "https://securite-sociale-alimentation.org/initiative/la-marmite-rouge/",
        "phone": "",
        "email": "lamarmiterouge@protonmail.com",
        "summary": "La Marmite Rouge est une association localisée dans le 12ème arrondissement de Paris, militant pour la Sécurité sociale de l’alimentation (SSA).",
        "URLs": [
            "https://www.facebook.com/p/La-Marmite-Rouge-100085215325610/"
        ]
    },
    {
        "name": "Collectif SSA-37",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["Collectif informel"],
        "Territoire d’expérimentation": "Touraine",
        "Partenaires": ["Confédération paysanne Touraine", "PSO/AA Touraine", "Université Populaire de la Terre", "Centres sociaux", "InPACT 37", "Les ami⋅es de la Confédération paysanne", "Naya", "Les jardiniers des Hucherolles de Chinon", "Ville de Tours"],
        "lat": 47.3941,
        "lng": 0.6848,
        "address": "Tours, France Centre-Val de Loire",
        "postcode": "37000",
        "city": "Tours",
        "website": "https://securite-sociale-alimentation.org/initiative/collectif-ssa-37/",
        "phone": "",
        "email": "",
        "summary": "En Touraine, nous sommes un collectif de 13 structures à s’être rassemblés pour contribuer à la dynamique nationale pour la mise en place de la Sécurité sociale de l’alimentation.",
        "URLs": [
            "https://osons.cc/p/ssa37/?PagePrincipale"
        ]
    },
    {
        "name": "L’ELFE, Epicerie Locale Favorisant l’Entraide",
        "type": "initiative SSA",
        "Structures porteuses": ["Association"],
        "Territoire d’expérimentation": "Brocéliande (communes rurales du Morbihan et d’Ille et Vilaine)",
        "Partenaires": [],
        "lat": 48.11360272054891,
        "lng": -2.067527352133475,
        "address": "35750 Saint-Gonlay, France",
        "postcode": "35750",
        "city": "Saint-Gonlay",
        "website": "https://securite-sociale-alimentation.org/initiative/lelfe-epicerie-locale-favorisant-lentraide/",
        "phone": "06.42.77.43.42",
        "email": "lelfe@riseup.net",
        "summary": "Création d’une épicerie solidaire mixte (ouverte à tou-te-s et itinérante) : projet qui tourne depuis deux ans avec une possibilité suivant sa situation sociale, financière etc d’accéder à des aliments locaux et de qualité à hauteur de 50 % du prix affiché.",
        "URLs": [
            "https://www.facebook.com/epiceriesolidaireenbroceliande",
            "https://lelfe.org"
        ]
    },
    {
        "name": "Comité local de l’alimentation",
        "type": "initiative SSA",
        "Structures porteuses": ["Au Maquis! - Association"],
        "Territoire d’expérimentation": "Sud Lubéron (Vaucluse)",
        "Partenaires": ["collectif informel : collectifs citoyens des villages alentours (Vaugines, Cucuron, Villelaure, Lauris, Mallemort…)", "Restaurant scolaire de Lauris", "Magasin de producteurs", "Secours Populaire", "Structures de l’ESS : Leris, laboratoire de recherche", "Collectivités locales (mairies, Pnrl)"],
        "lat": 43.746843268978125,
        "lng": 5.307884361056558,
        "address": "84360 Lauris, France",
        "postcode": "84360",
        "city": "Lauris",
        "website": "https://securite-sociale-alimentation.org/initiative/au-maquis/",
        "phone": "",
        "email": "",
        "summary": "La connaissance des causes permet de prendre de la hauteur avec sa propre vision. Il est particulièrement enrichissant d’échanger des points de vue parfois contradictoires, de construire un savoir et un horizon communs.",
        "URLs": [
            "https://www.aumaquis.org/"
        ]
    },
    {
        "name": "Comité local de l’alimentation",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["Association"],
        "Territoire d’expérimentation": "Saumurois",
        "Partenaires": [],
        "lat": 47.25971386233817,
        "lng": -0.07481046085842603,
        "address": "12, rue de la Tonnelle, 49400 Saumur",
        "postcode": "49400",
        "city": "Saumur",
        "website": "https://securite-sociale-alimentation.org/initiative/unipop-saumurois/",
        "phone": "07.81.14.01.14",
        "email": "contact@unipops.fr",
        "summary": "Un petit groupe informel d’habitants et d’habitantes qui se mobilisent pour diffuser l’idée de Sécurité sociale de l’alimentation sur leur territoire, auprès des élus etc…! Vous êtes du coin? Rejoignez-nous!",
        "URLs": [
            "https://unipopsaumurois.com/securite-sociale-alimentaire"
        ]
    },
    {
        "name": "Epicerie Paysanne Ambulante et Solidaire",
        "type": "initiative SSA",
        "Structures porteuses": ["Structure de l'ESS - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Haute-Vallée de l'Aude et Département de l'Aude",
        "Partenaires": ["La SCIC Maison Paysanne de l’Aude", "Nature et Progrès Aude", "la Confédération Paysanne de l’Aude", "le groupement d’achat la Musette", "les Jardins de la Haute-Vallée, coopérative de transformation de fruits et légumes", "le Secours Catholique Aude-Roussillon"],
        "lat": 43.047672933691395,
        "lng": 2.2229284499791984307884361056558,
        "address": "1 Avenue Salvador Allende, Limoux, France",
        "postcode": "11300",
        "city": "Limoux",
        "website": "https://securite-sociale-alimentation.org/initiative/epicerie-paysanne-ambulante-et-solidaire/",
        "phone": "",
        "email": "maisonpaysanne@mp11.fr",
        "summary": "La connaissance des causes permet de prendre de la hauteur avec sa propre vision. Il est particulièrement enrichissant d’échanger des points de vue parfois contradictoires, de construire un savoir et un horizon communs.",
        "URLs": [
            "https://www.maisonpaysanneaude.fr/epicerie-paysanne-aude/",
            "https://www.facebook.com/MaisonPaysanne11",
            "https://www.maisonpaysanneaude.fr"
        ]
    },
    {
        "name": "Local Attitude: une épicerie solidaire et participative mais ce n’est pas tout !",
        "type": "initiative SSA",
        "Structures porteuses": ["Association - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Bordeaux Nord",
        "Partenaires": ["Le Centre social de Grand-Parc, le Foyer fraternel, le Centre d’animation…", "L’association VRAC et d’autres associations autour de la solidarité alimentaire", "Les collectivités, dont la Mairie, le Département et la Région.", "Des fondations et fonds de dotation", "Des bailleurs sociaux", "Des mécènes, des entreprises à but lucratif", "Des élus de collectivités, des élus syndicaux, des élus politiques…"],
        "lat": 44.86456836833045, 
        "lng": -0.5819518094713092,
        "address": "Bordeaux Nord",
        "postcode": "33800",
        "city": "Bordeaux",
        "website": "https://securite-sociale-alimentation.org/initiative/local-attitude-une-epicerie-solidaire-et-participative/",
        "phone": "05 35 54 26 97",
        "email": "coordination.localattitude@gmail.com",
        "summary": "EpiC’tout kesako ? Une épicerie solidaire et participative portée par l’association Local’attitude. Elle fonctionne grâce à l’implication de nombreux bénévoles. Elle propose un principe de réciprocité, prend des chèques alimentaires permettant de faire ses courses à moitié prix, accueille, oriente et accompagne des personnes en difficulté.",
        "URLs": [
            "https://www.facebook.com/SocialeAlim"
        ]
    },
    {
        "name": "Vers une Sécurité Sociale de l’Alimentation à Dieulefit et alentours",
        "type": "initiative SSA",
        "Structures porteuses": ["Multiples - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Dieulefit et communauté de communes alentours",
        "Partenaires": [],
        "lat": 44.526725404152174, 
        "lng": 5.06157340380825,
        "address": "Dieulefit",
        "postcode": "26220",
        "city": "Dieulefit",
        "website": "https://securite-sociale-alimentation.org/initiative/autour-du-marche-du-lavoir/",
        "phone": "",
        "email": "caisse.alimentaire.ccdb@mailo.com",
        "summary": "Les personnes à l’initiative du projet ont mis en place un marché de vente avec un système de prix différenciés. Le marché est localisé dans un ancien lavoir désaffecté au coeur d’un quartier avec une population mixte. L’excédent ou le déficit du marché n’est pas à la charge du maraîcher mais est géré par une coffre physique, la caisse alimentaire, qui doit permettre de pérenniser le dispositif au fil du temps.",
        "URLs": []
    },
    {
        "name": "Collectif de réflexion et d’action sur la SSA en Belgique",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["Collectif informel - groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Bruxelles et Belgique francophone",
        "Partenaires": [],
        "lat": 50.82831935474033, 
        "lng": 4.369217825835658,
        "address": "Rue Van Elewyck, 35 1050 Bruxelles",
        "postcode": "1050",
        "city": "Bruxelles",
        "website": "https://securite-sociale-alimentation.org/initiative/groupe-de-reflexion-sur-la-ssa-a-bruxelles/",
        "phone": "",
        "email": "",
        "summary": "Le Collectif de réflexion et d’action sur la Sécurité sociale en Belgique ne fait pas à proprement partie du réseau mais nous tenions à mettre en avant ce Collectif qui travaille, en parallèle de nos avancées en France!",
        "URLs": [
            "https://www.collectif-ssa.be/"
        ]
    },
    {
        "name": "Pour une Sécurité sociale de l’alimentation – Alsace",
        "type": "initiative SSA",
        "Structures porteuses": ["Association, « Pour une Sécurité Sociale de l’Alimentation - Alsace » - groupe local et initiative locale vers une SSA"],
        "Territoire d’expérimentation": "Collectivité Européenne d’Alsace",
        "Partenaires": ["Projets Alimentaires Territoriaux de:, Eurométropole de Strasbourg, Mulhouse Alsace Agglomération, Pays du Sundgau", "Chambre Régionale d’Économie Sociale et Solidaire", "Alsace Active", "Programme Ticket for Change"],
        "lat": 48.259564608455534,
        "lng": 7.452926328337014,
        "address": "67600 Sélestat, France Grand Est",
        "postcode": "67600",
        "city": "Sélestat",
        "website": "https://securite-sociale-alimentation.org/initiative/mutuelle-de-lalimentation-en-alsace/",
        "phone": "",
        "email": "contact@mutuelle-alimentation-alsace.fr",
        "summary": "L’objectif est de s’inspirer du fonctionnement mutualiste pour créer une initiative locale la plus proche possible de la proposition de Sécurité sociale de l’alimentation.",
        "URLs": [
            "http://mutuelle-alimentation-alsace.fr/"
        ]
    },
    {
        "name": "Collectif Acclimat’action: pour réfléchir et expérimenter dans les quartiers populaires",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["Vrac Bordeaux", "les râteleurs", "supercoop", "capsciences", "CeDS", "Du vert dans les rouages", "e-graine", "L'estey", "Moisa et MIAM - acteurs issus de l’éducation populaire, de l’économie sociale et solidaire, du travail social ou de la recherche scientifique"],
        "Territoire d’expérimentation": "Bordeaux métropole et pays foyen",
        "Partenaires": ["l’ADEME", "la Région Nouvelle Aquitaine", "la Fondation Carasso", "la Fondation Européenne pour le Climat", "Bordeaux Métropole", "le Conseil Départemental de Gironde et la Ville de Bordeaux"],
        "lat": 44.87818660679672, 
        "lng": -0.5707916787261614,
        "address": "Avenue André Reinson, 33300 Bordeaux, Nouvelle-Aquitaine",
        "postcode": "33300",
        "city": "Bordeaux",
        "website": "https://securite-sociale-alimentation.org/initiative/collectif-acclimataction-pour-reflechir-et-experimenter-dans-les-quartiers-populaires/",
        "phone": "",
        "email": "",
        "summary": "Cette prise de hauteur se traduit chez les personnes par un « mélange d’indignation et d’envie d’agir »",
        "URLs": [
            "https://bordeaux.vrac-asso.org/",
            "https://vrac-asso.org/ressources/precarite-et-acces-a-une-alimentation-durable-a-la-fois-saine-et-ethique-des-enjeux-multiples/",
            "https://www.saluterre.com/"
        ]
    },
    {
        "name": "Caisse commune de l’alimentation Montpellier",
        "type": "initiative SSA",
        "Structures porteuses": ["Collectif informel - Collectif informel"],
        "Territoire d’expérimentation": "Montpellier",
        "Partenaires": ["Alternatiba", "ATD Quart-Monde", "CCAS", "Chaire Unesco Alimentation du Monde", "CIRAD", "CIVAM Bio 34", "Croix-Rouge Insertion", "EPSO – épicerie solidaire – Ugess", "FAS Occitanie", "FR CIVAM Occitanie", "Grenier d’abondance", "INPACT 34", "La 5e saison", "La cagette", "supermarché coopératif", "La Graine", "monnaie locale complémentaire", "L’esperluette-Celleneuve", "Marché paysan", "MIN de Montpellier", "Petits débrouillards 34", "Secours Catholique Hérault", "Semeurs de jardin", "SIAO", "Vobsalim", "Vrac & Cocinas"],
        "lat": 43.6119,
        "lng": 3.8772,
        "address": "Montpellier",
        "postcode": "34000",
        "city": "Montpellier",
        "website": "https://securite-sociale-alimentation.org/initiative/caisse-commune-de-lalimentation-montpellier/",
        "phone": "06 12 96 45 71",
        "email": "",
        "summary": "Un collectif informel de 25 organisations mobilisé pour monter une expérimentation autour de la démocratie alimentaire.",
        "URLs": ["https://tav-montpellier.xyz/?Experimentation"]
    },
    {
        "name": "Caissalim-Toulouse",
        "type": "initiative SSA",
        "Structures porteuses": ["Centre de recherche - initiative locale vers une SSA"],
        "Territoire d’expérimentation": "Aire urbaine toulousaine",
        "Partenaires": ["EDENN", "Cocagne Alimen’Terre", "Caracole et MAMA", "100e Singe et le LEGTA de Toulouse-Auzeville", "INRAE", "des étudiants de l’ENSAT et Sol Violette"],
        "lat": 43.643163344453434,
        "lng": 1.460984993000681,
        "address": "Toulouse",
        "postcode": "31000",
        "city": "Toulouse",
        "website": "https://securite-sociale-alimentation.org/initiative/caissalim-toulouse/",
        "phone": "",
        "email": "ssa.toulouse@gmail.com",
        "summary": "Expérimenter une sécurité sociale de l’alimentation dans la ville rose.",
        "URLs": [
            "http://www.caissalim-toulouse.org/"
        ]
    },
    {
        "name": "Etal Solidaire",
        "type": "initiative SSA",
        "Structures porteuses": ["Association - initiative locale vers une SSA"],
        "Territoire d’expérimentation": "Val de Marne / Ivry sur Seine",
        "Partenaires": ["Mairie d’Ivry sur Seine / Maisons des quartiers d’Ivry sur Seine", "La confédération paysanne", "Association Poignées d’entraide", "Association La parenthèse"],
        "lat": 48.81535780094634,
        "lng": 2.372974714684048,
        "address": "80 Rue Jules Ferry, 94200 Ivry-sur-Seine, France Île-de-France",
        "postcode": "94200",
        "city": "Ivry-sur-Seine",
        "website": "https://securite-sociale-alimentation.org/initiative/etal-solidaire/",
        "phone": "",
        "email": "",
        "summary": "Soutenir le travail du maraicher en favorisant la commercialisation de sa production, grâce aux bénévoles de l’étal solidaire. Chaque semaine, Didier ( notre producteur ) nous livre en direct de sa ferme du Nord-Pas-de-Calais des produits bios et de saison.",
        "URLs": [
            "https://etalsolidaire.org/",
            "www.facebook.com/etalsolidaire/"
        ]
    },
    {
        "name": "Collectif Alimentation et Agriculture durables de Cachan",
        "type": "initiative SSA",
        "Structures porteuses": ["Collectif informel - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Cachan",
        "Partenaires": ["Mairie d’Ivry sur Seine / Maisons des quartiers d’Ivry sur Seine", "La confédération paysanne", "Association Poignées d’entraide", "Association La parenthèse"],
        "lat": 48.7938138797509,
        "lng": 2.3341417569779055,
        "address": "Cachan",
        "postcode": "94230",
        "city": "Cachan",
        "website": "https://securite-sociale-alimentation.org/initiative/collectif-alimentation-et-agriculture-durables-de-cachan/",
        "phone": "",
        "email": "alimentationcachan@gmail.com",
        "summary": "Notre collectif s'est constitué après la découverte du projet de SSA à l'Université des mouvements sociaux de Nantes.",
        "URLs": []
    },
    {
        "name": "Collectif SSA22",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["Collectif informel - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Saint Brieuc Armor Agglomération",
        "Partenaires": ["La Fédération départementale des MJC qui nous accueille pour nos réunions"],
        "lat": 48.508056883552705, 
        "lng": -2.763036045452393,
        "address": "10 Boulevard Charner, 22000 Saint-Brieuc, Bretagne",
        "postcode": "22000",
        "city": "Saint-Brieuc",
        "website": "https://securite-sociale-alimentation.org/initiative/collectif-ssa22/",
        "phone": "",
        "email": "",
        "summary": "Pour communiquer, diffuser et défendre l’idée de Sécurité sociale de l’alimentation sur notre territoire",
        "URLs": [
            "https://www.facebook.com/people/Collectif-Ssa-St-Brieuc/100076064473121/"
        ]
    },
]
