// https://securite-sociale-alimentation.org/les-dynamiques-locales/carte-des-initiatives-locales-de-la-ssa/
var initiatives_ssa = [
    {
        "name": "Soli’Doume",
        "type": "initiative SSA",
        "Structures porteuses": ["ADML63", "le CRESNA", "VRAC Clermont-Ferrand", "Les Petits Débrouillards Auvergne"],
        "Territoire d’expérimentation": "Clermont-Ferrand",
        "Partenaires": ["CRESNA (coopérative)", "CISCA (recherche)"],
        "lat": 45.7741254,
        "lng": 3.0842469,
        "address": "Rue Meissonnier, 63000 Clermont-Ferrand, France Auvergne-Rhône-Alpes",
        "postcode": "63000",
        "city": "Clermont-Ferrand",
        "website": "https://securite-sociale-alimentation.org/initiative/la-doume/",
        "phone": "",
        "email": "",
        "summary": "L’équipe de l’Association pour le Développement des Monnaies Locales dans le Puy-de-Dôme a mis en place un travail de réflexion auprès de ses membres pour permettre l’accès de tous à une alimentation de qualité. (Monnaie Locale, coopérative)",
        "URLs": [
            "https://securite-sociale-alimentation.org/initiative/la-doume/"
        ]
    }
]

var initiatives_ssa2 = [
    {
        "name": "Collectif Acclimat’action",
        "type": "initiative SSA",
        "Structures porteuses": ["Vrac Bordeaux","les râteleurs","supercoop","capsciences","CeDS","Du vert dans les rouages","e-graine","L'estey","Moisa et MIAM - acteurs issus de l’éducation populaire de l’économie sociale et solidaire du travail social ou de la recherche scientifique"],
        "Territoire d’expérimentation": "Bordeaux métropole et pays foyen",
        "Partenaires": ["l’ADEME", "la Région Nouvelle Aquitaine", "la Fondation Carasso", "la Fondation Européenne pour le Climat", "Bordeaux Métropole", "le Conseil Départemental de Gironde et la Ville de Bordeaux"],
        "lat": 44.8775859,
        "lng": -0.5717582,
        "address": "Av. André Reinson",
        "postcode": "33300",
        "city": "Bordeaux",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour réfléchir et expérimenter dans les quartiers populaires",
        "URLs": ["https://www.acclimataction.fr/", "https://securite-sociale-alimentation.org/initiative/collectif-acclimataction-pour-reflechir-et-experimenter-dans-les-quartiers-populaires/"]
    },
    {
        "name": "Caisse commune de l’alimentation Montpellier",
        "type": "initiative SSA",
        "Structures porteuses": ["Réseau cocagne", "Secours Catholique France", "VRAC", "UGESS", "Réseau Civam"],
        "Territoire d’expérimentation": "Montpellier, France",
        "Partenaires": ["collectif national « Accès digne à l’alimentation »"],
        "lat": 43.6119,
        "lng": 3.8772,
        "address": "Montpellier",
        "postcode": "",
        "city": "Montpellier",
        "website": "https://tav-montpellier.xyz/?Experimentation",
        "phone": "",
        "email": "",
        "summary": "Un collectif informel de 25 organisations mobilisé pour monter une expérimentation autour de la démocratie alimentaire.",
        "URLs": ["https://tav-montpellier.xyz/?Experimentation"]
    },
    {
        "name": "Collectif SSA 35",
        "type": "initiative SSA",
        "Structures porteuses": ["Collectif informel - groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Ille-et-Vilaine (35)",
        "Partenaires": ["Alternatiba", "AMAP", "ATTAC Rennes", "CIVAM", "Le P’tit Blosneur", "Maison de la consommation et l’environnement"],
        "lat": 48.1173,
        "lng": -1.6778,
        "address": "Place de la Gare",
        "postcode": "35000",
        "city": "Rennes",
        "website": "",
        "phone": "",
        "email": "collectif-ssa35@protonmail.com",
        "summary": "Le Collectif SSA 35 mène différentes actions pour faire connaître la proposition politique au grand public et mobiliser pour la création de la SSA.",
        "URLs": []
    },
    {
        "name": "Bureaux SSA 33",
        "type": "initiative SSA",
        "Structures porteuses": ["ATD Quart Monde Gironde", "Collectif pour une transition citoyenne Gironde", "Réseau Salariat Gironde"],
        "Territoire d’expérimentation": "Bordeaux Métropole",
        "Partenaires": ["Les Amis de la Terre Gironde", "VRAC Bordeaux", "Les Landes Solidaires"],
        "lat": 44.8378,
        "lng": -0.5792,
        "address": "Bordeaux",
        "postcode": "",
        "city": "Bordeaux",
        "website": "https://securite-sociale-alimentation.org/bordeaux/",
        "phone": "",
        "email": "ssa.bordeaux@gmail.com",
        "summary": "Un lieu pour échanger et construire ensemble autour des questions alimentaires.",
        "URLs": ["https://securite-sociale-alimentation.org/bordeaux/"]
    },
    {
        "name": "Collectif SSA 69",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Lyon", "La Légumerie", "Les Petits Débrouillards Rhône-Alpes"],
        "Territoire d’expérimentation": "Lyon et ses environs",
        "Partenaires": ["La Gonette", "Cocagne Haute Dombes", "La Caravane des possibles"],
        "lat": 45.764043,
        "lng": 4.835659,
        "address": "Lyon",
        "postcode": "69000",
        "city": "Lyon",
        "website": "",
        "phone": "",
        "email": "collectifssa69@gmail.com",
        "summary": "Pour une sécurité sociale de l’alimentation dans la région lyonnaise.",
        "URLs": []
    },
    {
        "name": "SSA Toulouse",
        "type": "initiative SSA",
        "Structures porteuses": ["Les Amis de la Terre Midi-Pyrénées", "ATTAC Toulouse", "Réseau Salariat Toulouse"],
        "Territoire d’expérimentation": "Toulouse",
        "Partenaires": ["VRAC Toulouse", "Terre de liens Midi-Pyrénées", "ADEPES"],
        "lat": 43.6047,
        "lng": 1.4442,
        "address": "Toulouse",
        "postcode": "31000",
        "city": "Toulouse",
        "website": "",
        "phone": "",
        "email": "ssa.toulouse@gmail.com",
        "summary": "Expérimenter une sécurité sociale de l’alimentation dans la ville rose.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Grenoble",
        "type": "initiative SSA",
        "Structures porteuses": ["Les Habiles", "VRAC Grenoble", "Alliance PEC Isère"],
        "Territoire d’expérimentation": "Grenoble et son agglomération",
        "Partenaires": ["ATD Quart Monde", "ATTAC Isère", "Les Petits Débrouillards Isère"],
        "lat": 45.1885,
        "lng": 5.7245,
        "address": "Grenoble",
        "postcode": "38000",
        "city": "Grenoble",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Une dynamique locale pour la sécurité sociale de l’alimentation.",
        "URLs": []
    },
    {
        "name": "Collectif SSA 31",
        "type": "initiative SSA",
        "Structures porteuses": ["Réseau Salariat Haute-Garonne", "AMAP 31", "Terre de Liens"],
        "Territoire d’expérimentation": "Haute-Garonne",
        "Partenaires": ["ATTAC Toulouse", "Les Amis de la Terre Midi-Pyrénées"],
        "lat": 43.6043,
        "lng": 1.4437,
        "address": "Toulouse",
        "postcode": "",
        "city": "Toulouse",
        "website": "",
        "phone": "",
        "email": "ssa31@gmail.com",
        "summary": "Pour une alimentation digne et durable en Haute-Garonne.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Nantes",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Nantes", "Alliance PEC", "Réseau Salariat"],
        "Territoire d’expérimentation": "Nantes et sa métropole",
        "Partenaires": ["Les Amis de la Terre Loire-Atlantique", "ATTAC Nantes"],
        "lat": 47.2184,
        "lng": -1.5536,
        "address": "Nantes",
        "postcode": "44000",
        "city": "Nantes",
        "website": "",
        "phone": "",
        "email": "ssa.nantes@gmail.com",
        "summary": "Un collectif pour la sécurité sociale de l’alimentation à Nantes.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Lyon",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Lyon", "Les Petits Débrouillards Rhône-Alpes", "La Légumerie"],
        "Territoire d’expérimentation": "Lyon et alentours",
        "Partenaires": ["Cocagne Haute Dombes", "La Gonette", "La Caravane des possibles"],
        "lat": 45.764043,
        "lng": 4.835659,
        "address": "Lyon",
        "postcode": "69000",
        "city": "Lyon",
        "website": "",
        "phone": "",
        "email": "ssa.lyon@gmail.com",
        "summary": "Promotion de la sécurité sociale de l’alimentation dans la région lyonnaise.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Marseille",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Marseille", "Les Petits Débrouillards PACA", "Les Amis de la Terre PACA"],
        "Territoire d’expérimentation": "Marseille et environs",
        "Partenaires": ["ATTAC Marseille", "Réseau Salariat PACA"],
        "lat": 43.2965,
        "lng": 5.3698,
        "address": "Marseille",
        "postcode": "13000",
        "city": "Marseille",
        "website": "",
        "phone": "",
        "email": "ssa.marseille@gmail.com",
        "summary": "Initiative pour la sécurité sociale de l’alimentation à Marseille.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Lille",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Lille", "Les Petits Débrouillards Hauts-de-France"],
        "Territoire d’expérimentation": "Lille et Métropole Européenne de Lille",
        "Partenaires": ["ATTAC Lille", "Réseau Salariat Lille"],
        "lat": 50.6292,
        "lng": 3.0573,
        "address": "Lille",
        "postcode": "59000",
        "city": "Lille",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Lille et sa métropole.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Rouen",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Rouen", "AMAP Rouen", "Les Amis de la Terre Normandie"],
        "Territoire d’expérimentation": "Rouen et son agglomération",
        "Partenaires": ["ATTAC Rouen", "Réseau Salariat Rouen"],
        "lat": 49.4432,
        "lng": 1.0993,
        "address": "Rouen",
        "postcode": "76000",
        "city": "Rouen",
        "website": "",
        "phone": "",
        "email": "ssa.rouen@gmail.com",
        "summary": "Initiative pour une alimentation durable et solidaire à Rouen.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Strasbourg",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Strasbourg", "Les Petits Débrouillards Grand Est"],
        "Territoire d’expérimentation": "Strasbourg et sa région",
        "Partenaires": ["ATTAC Strasbourg", "Réseau Salariat Strasbourg"],
        "lat": 48.5734,
        "lng": 7.7521,
        "address": "Strasbourg",
        "postcode": "67000",
        "city": "Strasbourg",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Démarche pour une sécurité sociale de l’alimentation à Strasbourg.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Nantes Métropole",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Nantes Métropole", "Les Amis de la Terre 44"],
        "Territoire d’expérimentation": "Nantes Métropole",
        "Partenaires": ["ATTAC Nantes Métropole", "Réseau Salariat Nantes Métropole"],
        "lat": 47.2184,
        "lng": -1.5536,
        "address": "Nantes",
        "postcode": "44000",
        "city": "Nantes",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Promouvoir la sécurité sociale de l’alimentation à Nantes Métropole.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Tours",
        "type": "initiative SSA",
        "Structures porteuses": ["AMAP Tours", "Les Petits Débrouillards Centre-Val de Loire"],
        "Territoire d’expérimentation": "Tours et son agglomération",
        "Partenaires": ["ATTAC Tours", "Réseau Salariat Tours"],
        "lat": 47.3941,
        "lng": 0.6848,
        "address": "Tours",
        "postcode": "37000",
        "city": "Tours",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Initiative pour la sécurité sociale de l’alimentation à Tours.",
        "URLs": []
    },

    {
        "name": "Collectif SSA Perpignan",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Perpignan", "Les Petits Débrouillards Occitanie"],
        "Territoire d’expérimentation": "Perpignan et alentours",
        "Partenaires": ["ATTAC Perpignan", "Réseau Salariat Perpignan"],
        "lat": 42.6887,
        "lng": 2.8948,
        "address": "Perpignan",
        "postcode": "66000",
        "city": "Perpignan",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Perpignan.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Rennes Métropole",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Rennes Métropole", "Les Amis de la Terre Ille-et-Vilaine"],
        "Territoire d’expérimentation": "Rennes Métropole",
        "Partenaires": ["ATTAC Rennes Métropole", "Réseau Salariat Rennes Métropole"],
        "lat": 48.1173,
        "lng": -1.6778,
        "address": "Rennes",
        "postcode": "35000",
        "city": "Rennes",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Promouvoir la sécurité sociale de l’alimentation à Rennes Métropole.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Pau",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Pau", "Les Petits Débrouillards Nouvelle-Aquitaine"],
        "Territoire d’expérimentation": "Pau et Béarn",
        "Partenaires": ["ATTAC Pau", "Réseau Salariat Pau"],
        "lat": 43.2951,
        "lng": -0.3708,
        "address": "Pau",
        "postcode": "64000",
        "city": "Pau",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Démarche pour une sécurité sociale de l’alimentation à Pau.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Brest",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Brest", "Les Petits Débrouillards Bretagne"],
        "Territoire d’expérimentation": "Brest et Finistère",
        "Partenaires": ["ATTAC Brest", "Réseau Salariat Brest"],
        "lat": 48.3904,
        "lng": -4.4861,
        "address": "Brest",
        "postcode": "29200",
        "city": "Brest",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Brest.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Limoges",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Limoges", "Les Petits Débrouillards Limousin"],
        "Territoire d’expérimentation": "Limoges et Haute-Vienne",
        "Partenaires": ["ATTAC Limoges", "Réseau Salariat Limoges"],
        "lat": 45.8336,
        "lng": 1.2611,
        "address": "Limoges",
        "postcode": "87000",
        "city": "Limoges",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Limoges.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Metz",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Metz", "Les Petits Débrouillards Grand Est"],
        "Territoire d’expérimentation": "Metz et Moselle",
        "Partenaires": ["ATTAC Metz", "Réseau Salariat Metz"],
        "lat": 49.1193,
        "lng": 6.1757,
        "address": "Metz",
        "postcode": "57000",
        "city": "Metz",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Initiative pour une sécurité sociale de l’alimentation à Metz.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Bayonne",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Bayonne", "Les Petits Débrouillards Nouvelle-Aquitaine"],
        "Territoire d’expérimentation": "Bayonne et Pays Basque",
        "Partenaires": ["ATTAC Bayonne", "Réseau Salariat Bayonne"],
        "lat": 43.4929,
        "lng": -1.4748,
        "address": "Bayonne",
        "postcode": "64100",
        "city": "Bayonne",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Bayonne.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Montpellier Métropole",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Montpellier", "Les Petits Débrouillards Occitanie"],
        "Territoire d’expérimentation": "Montpellier Métropole",
        "Partenaires": ["ATTAC Montpellier", "Réseau Salariat Montpellier"],
        "lat": 43.6119,
        "lng": 3.8772,
        "address": "Montpellier",
        "postcode": "34000",
        "city": "Montpellier",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Initiative pour la sécurité sociale de l’alimentation à Montpellier Métropole.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Nancy",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Nancy", "Les Petits Débrouillards Grand Est"],
        "Territoire d’expérimentation": "Nancy et Lorraine",
        "Partenaires": ["ATTAC Nancy", "Réseau Salariat Nancy"],
        "lat": 48.6921,
        "lng": 6.1844,
        "address": "Nancy",
        "postcode": "54000",
        "city": "Nancy",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Nancy.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Dijon",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Dijon", "Les Petits Débrouillards Bourgogne"],
        "Territoire d’expérimentation": "Dijon et Côte-d'Or",
        "Partenaires": ["ATTAC Dijon", "Réseau Salariat Dijon"],
        "lat": 47.3220,
        "lng": 5.0415,
        "address": "Dijon",
        "postcode": "21000",
        "city": "Dijon",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Initiative pour la sécurité sociale de l’alimentation à Dijon.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Nice",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Nice", "Les Petits Débrouillards PACA"],
        "Territoire d’expérimentation": "Nice et Alpes-Maritimes",
        "Partenaires": ["ATTAC Nice", "Réseau Salariat Nice"],
        "lat": 43.7102,
        "lng": 7.2620,
        "address": "Nice",
        "postcode": "06000",
        "city": "Nice",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Démarche pour une sécurité sociale de l’alimentation à Nice.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Bordeaux Métropole",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Bordeaux", "Les Amis de la Terre Gironde"],
        "Territoire d’expérimentation": "Bordeaux Métropole",
        "Partenaires": ["ATTAC Bordeaux Métropole", "Réseau Salariat Bordeaux"],
        "lat": 44.8378,
        "lng": -0.5792,
        "address": "Bordeaux",
        "postcode": "33000",
        "city": "Bordeaux",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Initiative pour la sécurité sociale de l’alimentation à Bordeaux Métropole.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Caen",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Caen", "Les Petits Débrouillards Normandie"],
        "Territoire d’expérimentation": "Caen et Calvados",
        "Partenaires": ["ATTAC Caen", "Réseau Salariat Caen"],
        "lat": 49.1829,
        "lng": -0.3708,
        "address": "Caen",
        "postcode": "14000",
        "city": "Caen",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Caen.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Le Havre",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Le Havre", "Les Petits Débrouillards Normandie"],
        "Territoire d’expérimentation": "Le Havre et Seine-Maritime",
        "Partenaires": ["ATTAC Le Havre", "Réseau Salariat Le Havre"],
        "lat": 49.4944,
        "lng": 0.1079,
        "address": "Le Havre",
        "postcode": "76600",
        "city": "Le Havre",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Initiative pour une sécurité sociale de l’alimentation au Havre.",
        "URLs": []
    },
    {
        "name": "Collectif SSA La Rochelle",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC La Rochelle", "Les Petits Débrouillards Nouvelle-Aquitaine"],
        "Territoire d’expérimentation": "La Rochelle et Charente-Maritime",
        "Partenaires": ["ATTAC La Rochelle", "Réseau Salariat La Rochelle"],
        "lat": 46.1591,
        "lng": -1.1523,
        "address": "La Rochelle",
        "postcode": "17000",
        "city": "La Rochelle",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à La Rochelle.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Toulon",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Toulon", "Les Petits Débrouillards PACA"],
        "Territoire d’expérimentation": "Toulon et Var",
        "Partenaires": ["ATTAC Toulon", "Réseau Salariat Toulon"],
        "lat": 43.1242,
        "lng": 5.9280,
        "address": "Toulon",
        "postcode": "83000",
        "city": "Toulon",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Démarche pour une sécurité sociale de l’alimentation à Toulon.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Saint-Étienne",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Saint-Étienne", "Les Petits Débrouillards Auvergne-Rhône-Alpes"],
        "Territoire d’expérimentation": "Saint-Étienne et Loire",
        "Partenaires": ["ATTAC Saint-Étienne", "Réseau Salariat Saint-Étienne"],
        "lat": 45.4397,
        "lng": 4.3872,
        "address": "Saint-Étienne",
        "postcode": "42000",
        "city": "Saint-Étienne",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Initiative pour une sécurité sociale de l’alimentation à Saint-Étienne.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Reims",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Reims", "Les Petits Débrouillards Grand Est"],
        "Territoire d’expérimentation": "Reims et Champagne",
        "Partenaires": ["ATTAC Reims", "Réseau Salariat Reims"],
        "lat": 49.2583,
        "lng": 4.0317,
        "address": "Reims",
        "postcode": "51100",
        "city": "Reims",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Reims.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Grenoble Métropole",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Grenoble Métropole", "Les Petits Débrouillards Rhône-Alpes"],
        "Territoire d’expérimentation": "Grenoble Métropole",
        "Partenaires": ["ATTAC Grenoble Métropole", "Réseau Salariat Grenoble Métropole"],
        "lat": 45.1885,
        "lng": 5.7245,
        "address": "Grenoble",
        "postcode": "38000",
        "city": "Grenoble",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Promouvoir la sécurité sociale de l’alimentation à Grenoble Métropole.",
        "URLs": []
    }
];



