// https://securite-sociale-alimentation.org/les-dynamiques-locales/carte-des-initiatives-locales-de-la-ssa/
var initiatives_ssa = [
    {
        "name": "Soli’Doume",
        "type": "initiative SSA",
        "Structures porteuses": ["ADML63", "le CRESNA", "VRAC Clermont-Ferrand", "Les Petits Débrouillards Auvergne"],
        "Territoire d’expérimentation": "Clermont-Ferrand",
        "Partenaires": ["CRESNA (coopérative)", "CISCA (recherche)"],
        "lat": 45.7741254,
        "lng": 3.0842469,
        "address": "Rue Meissonnier, 63000 Clermont-Ferrand, France Auvergne-Rhône-Alpes",
        "postcode": "63000",
        "city": "Clermont-Ferrand",
        "website": "https://securite-sociale-alimentation.org/initiative/la-doume/",
        "phone": "",
        "email": "",
        "summary": "L’équipe de l’Association pour le Développement des Monnaies Locales dans le Puy-de-Dôme a mis en place un travail de réflexion auprès de ses membres pour permettre l’accès de tous à une alimentation de qualité. (Monnaie Locale, coopérative)",
        "URLs": [
            "www.cresna-intermediation.com",
            "www.doume.org"
        ]
    },
    {
        "name": "La cagette verte",
        "type": "initiative SSA",
        "Structures porteuses": ["ICARE - Association ICARE"],
        "Territoire d’expérimentation": "Saint-Quentin-en-Yvelines",
        "Partenaires": ["La faculté de Saint-Quentin-en-Yvelines"],
        "lat": 48.77888699840781,
        "lng": 2.045719679701665,
        "address": "Maison de l'étudiant 1 Allée de l'Astronomie, 78280 Guyancourt, France Île-de-France",
        "postcode": "78280",
        "city": "Guyancourt",
        "website": "https://securite-sociale-alimentation.org/initiative/la-cagette-verte/",
        "phone": "",
        "email": "",
        "summary": "La Cagette verte c’est un système d’AMAP à prix différencié organisé par et pour des étudiants!",
        "URLs": ["https://www.facebook.com/AssociationIcare"]
    },
    {
        "name": "Groupe local SSA Sud Ouest IDF",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": [],
        "Territoire d’expérimentation": "Versailles, Saint-Quentin-en-Yvelines, Saclay",
        "Partenaires": [],
        "lat": 48.788247377211704,
        "lng": 2.0473564968914766,
        "address": "1 Av. des Prés, 78180 Montigny-le-Bretonneux, France",
        "postcode": "78180",
        "city": "Montigny-le-Bretonneux",
        "website": "https://securite-sociale-alimentation.org/initiative/groupe-local-vsqy-saclay/",
        "phone": "",
        "email": "",
        "summary": "Déterminé à porter la proposition de Sécurité sociale de l’alimentation un groupe de militants et militantes s’organisent pour diffuser l’idée de Sécurité Sociale de l’Alimentation sur le territoire du sud Ouest de l’île de France. Plusieurs actions ont été mises en place : porteurs de paroles, ateliers de discussions, arpentages de livres, journées d’autoformation sur la sécurité sociale de l’alimentation etc … ",
        "URLs": []
    },
    {
        "name": "Manger Demain",
        "type": "initiative SSA",
        "Structures porteuses": ["Association - initiative locale vers une SSA"],
        "Territoire d’expérimentation": "Métropole Rouen Normandie / Région Normandie",
        "Partenaires": ["Le Producteur Local", "la Dantine", "Triticum", "Le Champ des Possibles", "Alternoo", "Groupe Nutriset", "Action Contre la Faim", "Chaire Unesco Alimentation du Monde"],
        "lat": 49.4432,
        "lng": 1.0993,
        "address": "Rouen",
        "postcode": "76000",
        "city": "Rouen",
        "website": "https://securite-sociale-alimentation.org/initiative/manger-demain/",
        "phone": "",
        "email": "",
        "summary": "Manger Demain, est un projet dédié à la sécurité alimentaire durable sur le territoire. L'objet du projet est de fédérer les acteurs locaux des systèmes alimentaires durables dans une approche systémique, pour accélérer l'évolution des modes de consommation alimentaires dans un enjeu de santé publique, et concevoir et expérimenter des systèmes d'accès pour tous à une alimentation durable dans un enjeu de droit à l'alimentation.",
        "URLs": []
    },
    {
        "name": "La Collab Solidaire",
        "type": "initiative SSA",
        "Structures porteuses": ["Association - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Hauts-de-France",
        "Partenaires": ["CSC Etouvie", "CS Elbeuf", "Relai social", "communes Helemmes", "Lille", "Flixecourt", "L’Etoile"],
        "lat": 50.6292,
        "lng": 3.0573,
        "address": "Lille",
        "postcode": "59000",
        "city": "Lille",
        "website": "https://securite-sociale-alimentation.org/initiative/collab-solidaire/",
        "phone": "",
        "email": "",
        "summary": "Mise en relation de producteurs locaux et d’associations pour proposer des produits de qualité à des prix accessibles ou gratuitement et sans condition selon les partenariats.",
        "URLs": []
    },
    {
        "name": "SSEA Trièves",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["CERES - groupe local et initiative de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Isère (38)",
        "Partenaires": [],
        "lat": 44.80092651475182,
        "lng": 5.647876014197057,
        "address": "Le Percy, 38930 Le Percy, Auvergne-Rhône-Alpes",
        "postcode": "38930",
        "city": "Le Percy",
        "website": "https://securite-sociale-alimentation.org/initiative/ssea-38/",
        "phone": "",
        "email": "associationceres@riseup.net",
        "summary": "Un collectif informel, porté par le CERES, qui regroupe de nombreuses structures et acteur.ices dans le Trièves. Nous nous réunissons pour travailler au maillage de notre territoire en lien avec la SSA et sur la faisabilité de construire une expérimentation.",
        "URLs": []
    },
    {
        "name": "La MEUP",
        "type": "initiative SSA",
        "Structures porteuses": ["Structure de l'ESS - initiative locale vers une SSA"],
        "Territoire d’expérimentation": "Secteur Paray-Vieille-Poste (91) et secteur de Rungis (94)",
        "Partenaires": ["PTCE Coop Communs", "PTCE Pôle Noé Coopérative", "Coop Communs Coopérative", "Nature Nourricière", "Coopérative ESSCOOP", "Ville de Paray-Vieille-Poste", "Etablissement Territorial Grand-Orly-Seine-Bièvre", "Club Francilien de l'EFC", "Association Le Théâtre du Fil"],
        "lat": 48.71259543816393,
        "lng": 2.3616348553956517,
        "address": "Paray-Vieille-Poste",
        "postcode": "91550",
        "city": "Paray-Vieille-Poste",
        "website": "https://securite-sociale-alimentation.org/initiative/la-meup-pour-lacceleration-de-la-transition-alimentaire-ecologique-et-sociale/",
        "phone": "",
        "email": "",
        "summary": "",
        "URLs": [
            "https://www.facebook.com/profile.php?id=100076181847462"
        ]
    },
    {
        "name": "Expérimentation d’une SSA pour les étudiant·es des campus bordelais",
        "type": "initiative SSA",
        "Structures porteuses": ["Multiples - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Bordeaux Métropole",
        "Partenaires": ["La GEMME", "Le CREPAQ", "VRAC Université", "La cuvée des écolos", "Bordeaux Métropole", "CCAS de Bordeaux", "Université Bordeaux Montaigne", "Université de Bordeaux", "Ville de Pessac", "SICA Maraichère Bordelaise", "RESES", "La Fédération ATENA", "Ingénieurs Sans Frontières", "Bordeaux Sciences Agro", "une 20aine d’étudiant·es"],
        "lat": 44.83064510417015, 
        "lng": -0.5656059499354108,
        "address": "6 rue des Douves 33800 Bordeaux",
        "postcode": "33800",
        "city": "Bordeaux",
        "website": "https://securite-sociale-alimentation.org/initiative/projet-dexperimentation-dune-securite-sociale-de-lalimentation-pour-les-etudiant%c2%b7es-des-campus-bordelais/",
        "phone": "05 35 54 26 97",
        "email": "contact@crepaq.ong",
        "summary": "",
        "URLs": [
            "https://www.crepaq.ong/ssa%C3%A9tudiante",
        ]
    },
    {
        "name": "Collectif SSA 35",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["Collectif informel - groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Ille-et-Vilaine (35)",
        "Partenaires": [],
        "lat": 48.10387821015734,
        "lng": -1.67052829575318,
        "address": "Place de la Gare, 35000 Rennes, France",
        "postcode": "35000",
        "city": "Rennes",
        "website": "https://securite-sociale-alimentation.org/initiative/collectif-ssa-35/",
        "phone": "",
        "email": "collectif-ssa35@protonmail.com",
        "summary": "Le Collectif SSA 35 mène différentes actions pour faire connaître la proposition politique au grand public et mobiliser pour la création de la SSA.",
        "URLs": []
    },
    {
        "name": "Conserverie solidaire",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["Association - groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Saint-Denis, Stains",
        "Partenaires": [],
        "lat": 48.94598112524915,
        "lng": 2.3733663109107876,
        "address": "Saint-Denis/Stains, France",
        "postcode": "93240",
        "city": "Stains",
        "website": "https://securite-sociale-alimentation.org/initiative/conserverie-solidaire/",
        "phone": "",
        "email": "",
        "summary": "L’association collecte des fruits et légumes abîmés, les transforme en confitures et les re-distribue sur evènements ciblés ou auprès de population plus fragile telles que les étudiants de paris 8 ou les mineurs migrants.",
        "URLs": []
    },
    {
        "name": "Caisse de l’alimentation – Territoires à VivreS Grand Lyon",
        "type": "initiative SSA",
        "Structures porteuses": ["Association - initiative locale vers une SSA"],
        "Territoire d’expérimentation": "L'aire urbaine de Lyon, et en particulier l'arrondissement de Lyon 8",
        "Partenaires": ["VRAC Lyon Métropole", "le Groupement des Epiceries Sociales et Solidaires Rhône Alpes", "Habitat et Humanisme Rhône", "le Secours Catholique du Rhône", "le Groupement Régional Alimentaire de Proximité (GRAP)", "Récup & Gamelles", "Agribio", "l'UGESS", "la Fédération des Centres Sociaux du Rhône", "Bellebouffe", "Epi c'est bon", "l'ADDEAR", "le Réseau AMAP Aura", "Epicentre", "l'ISARA", "Bio à pro", "l'Espace Créateur de Solidarité de Saint-Fons", "la Maison Engagée et Solidaire de l'Alimentation", "les Jardins de Lucie", "la Métropole de Lyon"],
        "lat": 45.70769409083929,
        "lng": 4.869807983240429,
        "address": "41 avenue de la république, 69200 Vénissieux",
        "postcode": "69200",
        "city": "Lyon",
        "website": "https://securite-sociale-alimentation.org/initiative/caisse-de-lalimentation-territoires-a-vivres-grand-lyon/",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation dans la région lyonnaise.",
        "URLs": [
            "https://tav-lyon.xyz/?PagePrincipale",
            "https://www.linkedin.com/company/territoires-%C3%A0-vivres-grand-lyon/"
        ]
    },
    {
        "name": "SoliCagnole ",
        "type": "initiative SSA",
        "Structures porteuses": ["Association dédiée SoliCagnole - initiative locale vers une SSA"],
        "Territoire d’expérimentation": "Yonne et alentours",
        "Partenaires": ["Monnaie locale de l’Yonne La Cagnole", "Terre de Liens Bourgogne Franche-Comté", "Groupement des AgroBiologistes de l’Yonne"],
        "lat": 47.8588857621887,
        "lng": 3.4465699790519695,
        "address": "1 chemin de Charbuy 89113 Fleury-la-Vallée",
        "postcode": "89113",
        "city": "Fleury-la-Vallée",
        "website": "https://securite-sociale-alimentation.org/initiative/solicagnole/",
        "phone": "",
        "email": "secretariat@solicagnole.fr",
        "summary": "L’association Courts Circuits La Cagnole veut mettre en place une Sécurité Sociale de l’Alimentation, faisant de l’accessibilité à une alimentation soutenable et saine, un droit pour tous. Concrètement, chacun cotise chaque mois, selon ses moyens, de 10 à 100 Euros (ou plus) et tout le monde reçoit la même somme (la moyenne des cotisations) en monnaie locale, somme qui ne peut être dépensée qu’auprès de nos partenaires (producteurs et magasins bio, épiceries sociales et solidaires, épiceries indépendantes). Nous comptons co-créer une association dédiée à cette caisse, transparente et démocratique.",
        "URLs": [
            "https://solicagnole.fr/"
        ]
    },
    {
        "name": "Couserans (CAC09) – Ariège",
        "type": "initiative SSA",
        "Structures porteuses": ["Multiples - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Saint-Girons - Couserans en Ariège",
        "Partenaires": ["Croix Rouge", "Biocoop", "Secours Catholiques", "des élus à la mairie de St Girons", "une élue régionale sur la précarité alimentaire", "PNR des Pyrénées Ariégeoises et des bénévoles… + d’autres à solliciter! CAF", "projet de recherche participative HmmLab: INRAE (UMR Agir)", "ISTHIA", "PNR des Pyrénées Ariégeoises", "les Biches Volantes"],
        "lat": 42.982897312581485,
        "lng": 1.146062941970322,
        "address": "Saint-Girons",
        "postcode": "09200",
        "city": "Saint-Girons",
        "website": "https://securite-sociale-alimentation.org/initiative/citoyennete-et-alimentation-en-couserans-cac09-ariege/",
        "phone": "",
        "email": "",
        "summary": "Pour une alimentation digne et durable en Haute-Garonne.",
        "URLs": [
            "https://www.bio-ariege-garonne.fr/article/accessibilite-alimentaire"
        ]
    },
    {
        "name": "Groupe local SSA 38",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["Collectif informel - groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Isère (38)",
        "Partenaires": [],
        "lat": 45.187855539457395,
        "lng": 5.723092297478416,
        "address": "",
        "postcode": "",
        "city": "",
        "website": "https://securite-sociale-alimentation.org/initiative/groupe-local-ssa-38/",
        "phone": "",
        "email": "gl-ssa38@gresille.org",
        "summary": "",
        "URLs": []
    },
    {
        "name": "Caisse sociale de l’alimentation",
        "type": "initiative SSA",
        "Structures porteuses": ["Structure de l'ESS - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "Saint-Etienne et alentours",
        "Partenaires": ["Terrain d’entente", "les Brigades de solidarité", "la Fourmilière", "la Cantine de quartier du Crêt-de-Roch", "les AMAPs de la Loire", "l’AMAP de Beaubrun", "De la Ferme au Quartier", "VRAC Saint Etienne", "la Biocoop des arcades", "Oasis", "Au terroir", "Danae care", "Coop’Sol42 et la Fabrique de la transition"],
        "lat": 45.4392528202996,
        "lng": 4.383286778007318,
        "address": "Saint-Étienne",
        "postcode": "42000",
        "city": "Saint-Étienne",
        "website": "https://securite-sociale-alimentation.org/initiative/collectif-solidarite-alimentaire-ssa42/",
        "phone": "",
        "email": "",
        "summary": "Initiative pour une sécurité sociale de l’alimentation à Saint-Étienne.",
        "URLs": []
    },
    {
        "name": "La Marmite Rouge",
        "type": "initiative SSA",
        "Structures porteuses": ["Association - initiative et groupe local de réflexion vers une SSA"],
        "Territoire d’expérimentation": "12ème arrondissement et Est Parisien",
        "Partenaires": [],
        "lat": 45.4392528202996,
        "lng": 4.383286778007318,
        "address": "181 Avenue Daumesnil, 75012 Paris, France Île-de-France",
        "postcode": "75012",
        "city": "Paris",
        "website": "https://securite-sociale-alimentation.org/initiative/la-marmite-rouge/",
        "phone": "",
        "email": "lamarmiterouge@protonmail.com",
        "summary": "La Marmite Rouge est une association localisée dans le 12ème arrondissement de Paris, militant pour la Sécurité sociale de l’alimentation (SSA).",
        "URLs": [
            "https://www.facebook.com/p/La-Marmite-Rouge-100085215325610/"
        ]
    },
    {
        "name": "Collectif SSA-37",
        "type": "Groupe local pour une SSA",
        "Structures porteuses": ["Collectif informel"],
        "Territoire d’expérimentation": "Touraine",
        "Partenaires": ["Confédération paysanne Touraine", "PSO/AA Touraine", "Université Populaire de la Terre", "Centres sociaux", "InPACT 37", "Les ami⋅es de la Confédération paysanne", "Naya", "Les jardiniers des Hucherolles de Chinon", "Ville de Tours"],
        "lat": 47.3941,
        "lng": 0.6848,
        "address": "Tours, France Centre-Val de Loire",
        "postcode": "37000",
        "city": "Tours",
        "website": "https://securite-sociale-alimentation.org/initiative/collectif-ssa-37/",
        "phone": "",
        "email": "",
        "summary": "En Touraine, nous sommes un collectif de 13 structures à s’être rassemblés pour contribuer à la dynamique nationale pour la mise en place de la Sécurité sociale de l’alimentation.",
        "URLs": [
            "https://osons.cc/p/ssa37/?PagePrincipale"
        ]
    },
]

var initiatives_ssa2 = [
    {
        "name": "Caisse commune de l’alimentation Montpellier",
        "type": "initiative SSA",
        "Structures porteuses": ["Réseau cocagne", "Secours Catholique France", "VRAC", "UGESS", "Réseau Civam"],
        "Territoire d’expérimentation": "Montpellier, France",
        "Partenaires": ["collectif national « Accès digne à l’alimentation »"],
        "lat": 43.6119,
        "lng": 3.8772,
        "address": "Montpellier",
        "postcode": "",
        "city": "Montpellier",
        "website": "https://tav-montpellier.xyz/?Experimentation",
        "phone": "",
        "email": "",
        "summary": "Un collectif informel de 25 organisations mobilisé pour monter une expérimentation autour de la démocratie alimentaire.",
        "URLs": ["https://tav-montpellier.xyz/?Experimentation"]
    },


    {
        "name": "SSA Toulouse",
        "type": "initiative SSA",
        "Structures porteuses": ["Les Amis de la Terre Midi-Pyrénées", "ATTAC Toulouse", "Réseau Salariat Toulouse"],
        "Territoire d’expérimentation": "Toulouse",
        "Partenaires": ["VRAC Toulouse", "Terre de liens Midi-Pyrénées", "ADEPES"],
        "lat": 43.6047,
        "lng": 1.4442,
        "address": "Toulouse",
        "postcode": "31000",
        "city": "Toulouse",
        "website": "",
        "phone": "",
        "email": "ssa.toulouse@gmail.com",
        "summary": "Expérimenter une sécurité sociale de l’alimentation dans la ville rose.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Grenoble",
        "type": "initiative SSA",
        "Structures porteuses": ["Les Habiles", "VRAC Grenoble", "Alliance PEC Isère"],
        "Territoire d’expérimentation": "Grenoble et son agglomération",
        "Partenaires": ["ATD Quart Monde", "ATTAC Isère", "Les Petits Débrouillards Isère"],
        "lat": 45.1885,
        "lng": 5.7245,
        "address": "Grenoble",
        "postcode": "38000",
        "city": "Grenoble",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Une dynamique locale pour la sécurité sociale de l’alimentation.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Nantes",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Nantes", "Alliance PEC", "Réseau Salariat"],
        "Territoire d’expérimentation": "Nantes et sa métropole",
        "Partenaires": ["Les Amis de la Terre Loire-Atlantique", "ATTAC Nantes"],
        "lat": 47.2184,
        "lng": -1.5536,
        "address": "Nantes",
        "postcode": "44000",
        "city": "Nantes",
        "website": "",
        "phone": "",
        "email": "ssa.nantes@gmail.com",
        "summary": "Un collectif pour la sécurité sociale de l’alimentation à Nantes.",
        "URLs": []
    },

    {
        "name": "Collectif SSA Marseille",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Marseille", "Les Petits Débrouillards PACA", "Les Amis de la Terre PACA"],
        "Territoire d’expérimentation": "Marseille et environs",
        "Partenaires": ["ATTAC Marseille", "Réseau Salariat PACA"],
        "lat": 43.2965,
        "lng": 5.3698,
        "address": "Marseille",
        "postcode": "13000",
        "city": "Marseille",
        "website": "",
        "phone": "",
        "email": "ssa.marseille@gmail.com",
        "summary": "Initiative pour la sécurité sociale de l’alimentation à Marseille.",
        "URLs": []
    },

    {
        "name": "Collectif SSA Strasbourg",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Strasbourg", "Les Petits Débrouillards Grand Est"],
        "Territoire d’expérimentation": "Strasbourg et sa région",
        "Partenaires": ["ATTAC Strasbourg", "Réseau Salariat Strasbourg"],
        "lat": 48.5734,
        "lng": 7.7521,
        "address": "Strasbourg",
        "postcode": "67000",
        "city": "Strasbourg",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Démarche pour une sécurité sociale de l’alimentation à Strasbourg.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Nantes Métropole",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Nantes Métropole", "Les Amis de la Terre 44"],
        "Territoire d’expérimentation": "Nantes Métropole",
        "Partenaires": ["ATTAC Nantes Métropole", "Réseau Salariat Nantes Métropole"],
        "lat": 47.2184,
        "lng": -1.5536,
        "address": "Nantes",
        "postcode": "44000",
        "city": "Nantes",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Promouvoir la sécurité sociale de l’alimentation à Nantes Métropole.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Perpignan",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Perpignan", "Les Petits Débrouillards Occitanie"],
        "Territoire d’expérimentation": "Perpignan et alentours",
        "Partenaires": ["ATTAC Perpignan", "Réseau Salariat Perpignan"],
        "lat": 42.6887,
        "lng": 2.8948,
        "address": "Perpignan",
        "postcode": "66000",
        "city": "Perpignan",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Perpignan.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Rennes Métropole",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Rennes Métropole", "Les Amis de la Terre Ille-et-Vilaine"],
        "Territoire d’expérimentation": "Rennes Métropole",
        "Partenaires": ["ATTAC Rennes Métropole", "Réseau Salariat Rennes Métropole"],
        "lat": 48.1173,
        "lng": -1.6778,
        "address": "Rennes",
        "postcode": "35000",
        "city": "Rennes",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Promouvoir la sécurité sociale de l’alimentation à Rennes Métropole.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Pau",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Pau", "Les Petits Débrouillards Nouvelle-Aquitaine"],
        "Territoire d’expérimentation": "Pau et Béarn",
        "Partenaires": ["ATTAC Pau", "Réseau Salariat Pau"],
        "lat": 43.2951,
        "lng": -0.3708,
        "address": "Pau",
        "postcode": "64000",
        "city": "Pau",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Démarche pour une sécurité sociale de l’alimentation à Pau.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Brest",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Brest", "Les Petits Débrouillards Bretagne"],
        "Territoire d’expérimentation": "Brest et Finistère",
        "Partenaires": ["ATTAC Brest", "Réseau Salariat Brest"],
        "lat": 48.3904,
        "lng": -4.4861,
        "address": "Brest",
        "postcode": "29200",
        "city": "Brest",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Brest.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Limoges",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Limoges", "Les Petits Débrouillards Limousin"],
        "Territoire d’expérimentation": "Limoges et Haute-Vienne",
        "Partenaires": ["ATTAC Limoges", "Réseau Salariat Limoges"],
        "lat": 45.8336,
        "lng": 1.2611,
        "address": "Limoges",
        "postcode": "87000",
        "city": "Limoges",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Limoges.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Metz",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Metz", "Les Petits Débrouillards Grand Est"],
        "Territoire d’expérimentation": "Metz et Moselle",
        "Partenaires": ["ATTAC Metz", "Réseau Salariat Metz"],
        "lat": 49.1193,
        "lng": 6.1757,
        "address": "Metz",
        "postcode": "57000",
        "city": "Metz",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Initiative pour une sécurité sociale de l’alimentation à Metz.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Bayonne",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Bayonne", "Les Petits Débrouillards Nouvelle-Aquitaine"],
        "Territoire d’expérimentation": "Bayonne et Pays Basque",
        "Partenaires": ["ATTAC Bayonne", "Réseau Salariat Bayonne"],
        "lat": 43.4929,
        "lng": -1.4748,
        "address": "Bayonne",
        "postcode": "64100",
        "city": "Bayonne",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Bayonne.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Montpellier Métropole",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Montpellier", "Les Petits Débrouillards Occitanie"],
        "Territoire d’expérimentation": "Montpellier Métropole",
        "Partenaires": ["ATTAC Montpellier", "Réseau Salariat Montpellier"],
        "lat": 43.6119,
        "lng": 3.8772,
        "address": "Montpellier",
        "postcode": "34000",
        "city": "Montpellier",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Initiative pour la sécurité sociale de l’alimentation à Montpellier Métropole.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Nancy",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Nancy", "Les Petits Débrouillards Grand Est"],
        "Territoire d’expérimentation": "Nancy et Lorraine",
        "Partenaires": ["ATTAC Nancy", "Réseau Salariat Nancy"],
        "lat": 48.6921,
        "lng": 6.1844,
        "address": "Nancy",
        "postcode": "54000",
        "city": "Nancy",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Nancy.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Dijon",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Dijon", "Les Petits Débrouillards Bourgogne"],
        "Territoire d’expérimentation": "Dijon et Côte-d'Or",
        "Partenaires": ["ATTAC Dijon", "Réseau Salariat Dijon"],
        "lat": 47.3220,
        "lng": 5.0415,
        "address": "Dijon",
        "postcode": "21000",
        "city": "Dijon",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Initiative pour la sécurité sociale de l’alimentation à Dijon.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Nice",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Nice", "Les Petits Débrouillards PACA"],
        "Territoire d’expérimentation": "Nice et Alpes-Maritimes",
        "Partenaires": ["ATTAC Nice", "Réseau Salariat Nice"],
        "lat": 43.7102,
        "lng": 7.2620,
        "address": "Nice",
        "postcode": "06000",
        "city": "Nice",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Démarche pour une sécurité sociale de l’alimentation à Nice.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Caen",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Caen", "Les Petits Débrouillards Normandie"],
        "Territoire d’expérimentation": "Caen et Calvados",
        "Partenaires": ["ATTAC Caen", "Réseau Salariat Caen"],
        "lat": 49.1829,
        "lng": -0.3708,
        "address": "Caen",
        "postcode": "14000",
        "city": "Caen",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Caen.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Le Havre",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Le Havre", "Les Petits Débrouillards Normandie"],
        "Territoire d’expérimentation": "Le Havre et Seine-Maritime",
        "Partenaires": ["ATTAC Le Havre", "Réseau Salariat Le Havre"],
        "lat": 49.4944,
        "lng": 0.1079,
        "address": "Le Havre",
        "postcode": "76600",
        "city": "Le Havre",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Initiative pour une sécurité sociale de l’alimentation au Havre.",
        "URLs": []
    },
    {
        "name": "Collectif SSA La Rochelle",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC La Rochelle", "Les Petits Débrouillards Nouvelle-Aquitaine"],
        "Territoire d’expérimentation": "La Rochelle et Charente-Maritime",
        "Partenaires": ["ATTAC La Rochelle", "Réseau Salariat La Rochelle"],
        "lat": 46.1591,
        "lng": -1.1523,
        "address": "La Rochelle",
        "postcode": "17000",
        "city": "La Rochelle",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à La Rochelle.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Toulon",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Toulon", "Les Petits Débrouillards PACA"],
        "Territoire d’expérimentation": "Toulon et Var",
        "Partenaires": ["ATTAC Toulon", "Réseau Salariat Toulon"],
        "lat": 43.1242,
        "lng": 5.9280,
        "address": "Toulon",
        "postcode": "83000",
        "city": "Toulon",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Démarche pour une sécurité sociale de l’alimentation à Toulon.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Reims",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Reims", "Les Petits Débrouillards Grand Est"],
        "Territoire d’expérimentation": "Reims et Champagne",
        "Partenaires": ["ATTAC Reims", "Réseau Salariat Reims"],
        "lat": 49.2583,
        "lng": 4.0317,
        "address": "Reims",
        "postcode": "51100",
        "city": "Reims",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Pour une sécurité sociale de l’alimentation à Reims.",
        "URLs": []
    },
    {
        "name": "Collectif SSA Grenoble Métropole",
        "type": "initiative SSA",
        "Structures porteuses": ["VRAC Grenoble Métropole", "Les Petits Débrouillards Rhône-Alpes"],
        "Territoire d’expérimentation": "Grenoble Métropole",
        "Partenaires": ["ATTAC Grenoble Métropole", "Réseau Salariat Grenoble Métropole"],
        "lat": 45.1885,
        "lng": 5.7245,
        "address": "Grenoble",
        "postcode": "38000",
        "city": "Grenoble",
        "website": "",
        "phone": "",
        "email": "",
        "summary": "Promouvoir la sécurité sociale de l’alimentation à Grenoble Métropole.",
        "URLs": []
    }
];



